.Dd $Mdocdate$
.Dt TERMUX-USER-FIX(7)
.Sh termux-user-fix
.Nm termux-user-fix
.Nd Fixes the displayed user and group names.
.Sh SYNOPSIS
.Nm export LD_PRELOAD="$LD_PRELOAD:$PREFIX/lib/libfixuser.so"
.Sh DESCRIPTION
.Nm termux-user-fix
Fixes the displayed user and group names by intercepting the library calls that get the names.

To use, put the export statement above in your .bashrc.
